// `.env.json` is generated by the `npm run build` command
import env from './.env.json';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://club-seyssins-bridge.7e14.starter-us-west-2.openshiftapps.com/api',
  mapAPI: 'AIzaSyC0A5qHEGVF-gHuk6VmXRHjkaue12H6EsM',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
