// `.env.json` is generated by the `npm run build` command
import env from './.env.json';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://tranquil-falls-51950.herokuapp.com/api',
  mapAPI: 'AIzaSyC0A5qHEGVF-gHuk6VmXRHjkaue12H6EsM',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
